---
- name: Wait before connecting to host
  wait_for_connection:
    delay: 30
    timeout: 300
    
- name: Install nginx
  package:
    name:
      - nginx

- name: Copy files
  ansible.builtin.copy:
    src: html/
    dest: /var/www/html/
    mode: 0644
