---

- name: Create VMs
  hosts: localhost
  vars_prompt:
  - name: keypair
    prompt: Configured key pair name. Must be in OpenStack already
    private: false
  - name: network
    prompt: Network that the VM(s) will be attached to
    private: false
  roles:
    - terraform

- name: Configure VMs
  hosts: created_instances
  gather_facts: false
  become: true
  roles:
    - nginx
