---
- name: Run Terraform
  terraform:
    project_path: "{{ playbook_dir }}/terraform"
    state: "{{ state | default('present') }}"
    workspace: default
    # Here we can override variables defined within the Terraform modules
    # Note that all variables that we want to override need to be present
    # in main.tf, even though they might be defined in a module
    # Needs ansible >2.10
    variables:
      network: "{{ network }}"
      keypair: "{{ keypair }}"
    variables_files:
    - "{{ playbook_dir }}/terraform/variables.tfvars"
  register: server_facts

# Now iterate over the list returned by Terraform and build
# the inventory accordingly.
- name: Add entries to inventory
  add_host:
    name: "{{ item.name }}"
    ansible_ssh_host: "{{ item.ip }}"
    ansible_ssh_user: "{{ item.ansible_ssh_user }}"
    host_key_checking: false
    groups: "{{ item.groups  }}"
    ansible_ssh_common_args: "{{ item.ssh_args }}"
  when: item.name not in hostvars.keys()
  loop: "{{ server_facts.outputs.inventory.value }}"
